service::gitupdate: Remove node_modules/ before installing the new ones
Most of our Node.JS services use the '^x.x.x' format for specifying the
dependencies' versions to use. When `npm install` is run, it doesn't
check for newer versions if the currently-installed module satisfies the
version. Hence, we need to force npm to install the new versions by
removing the old module dependencies first.

This patch also brings several improvements to vagrant's git-update
command. First, it exposes the environment variables needed by NPM
during the installation process (much like during the initial npm
install on role enabling), allowing for binary modules to be built.
Secondly, it clears the NPM cache before the update process; NPM uses
the cache to compare the versions, which is deadly for large modules
containing binaries as that is known to cause NPM OOMs. Finally, do
not proceed to restarting the service if the update of dependencies
has failed.

Also, update the RESTBase configuration to the current master state.

Change-Id: Ie4769e123850d4ff4da24a22834b2c5d3d03586f

diff --git a/puppet/modules/mediawiki/templates/run-git-update.erb b/puppet/modules/mediawiki/templates/run-git-update.erb
--- a/puppet/modules/mediawiki/templates/run-git-update.erb
+++ b/puppet/modules/mediawiki/templates/run-git-update.erb
@@ -62,7 +62,18 @@ function pull {
 
 }
 
+# expose the needed npm env vars
+export NPM_CONFIG_CACHE="<%= scope['::npm::cache_dir'] %>"
+export NPM_CONFIG_GLOBAL=false
+export LINK=g++
+export HOME=/home/vagrant
+
+# clear the npm module cache as earlier cached versions
+# of larger modules cause npm to run out of memory
+sudo rm -rf <%= scope['::npm::cache_dir'] %>/* /home/vagrant/.npm
+
 for srvconf in <%= scope['::service::conf_dir'] %>/*.conf; do
+  err=''
   source ${srvconf}
   echo -e "\e[36m==> Updating ${SERVICE_NAME} ...\e[0m"
   if [[ -n "${NEED_CHDIR}" && -d ${SERVICE_DIR} ]]; then
@@ -70,10 +81,14 @@ for srvconf in <%= scope['::service::conf_dir'] %>/*.conf; do
     [[ -n "${DO_PULL}" ]] && pull no_title
     if [[ -n ${UPDATE_CMD} ]]; then
       echo "[*] Updating dependencies for ${SERVICE_NAME} ..."
-      ${UPDATE_CMD}
+      if ! /bin/sh -c "${UPDATE_CMD}"; then
+        err="Could not update dependencies of ${SERVICE_NAME} !"
+        echo -e "\e[1;31m ***** $err\e[0m"
+        UPDATE_ERRORS+=("${err}")
+      fi
     fi
   fi
-  if [[ -n "${DO_RESTART}" ]]; then
+  if [[ -n "${DO_RESTART}" && -z "${err}" ]]; then
     echo "[*] Restarting service ${RESTART_NAME} ..."
     sudo service ${RESTART_NAME} restart
   fi
