Improved error messages for git-update command
Change-Id: I87bb3220689603028f3eac323f0f0b2ddc5f4d95

diff --git a/puppet/modules/mediawiki/files/run-git-update b/puppet/modules/mediawiki/files/run-git-update
--- a/puppet/modules/mediawiki/files/run-git-update
+++ b/puppet/modules/mediawiki/files/run-git-update
@@ -1,29 +1,39 @@
 #!/bin/bash
 . /etc/profile.d/puppet-managed/set_mw_install_path.sh
 
+set -u
+declare -a errors
+
 function pull {
   echo
   branch=$(expr $(git symbolic-ref HEAD) : 'refs/heads/\(.*\)')
+  err=''
   if [ -n "$branch" ]; then
     remote=$(git config branch.$branch.remote)
     if [ -n "$remote" ]; then
         url=$(git config --get remote.$remote.url)
-        if [[ $url == ssh://* ]]
-        then
+        if [[ $url == ssh://* ]]; then
             # Convert remote git url from ssh:// to anonymous https://
             tempurl=$(echo $url | sed -e 's!ssh://[^@]\+@!https://!g' -e 's!:29418!/r!g')
             git pull $tempurl
         else
             git pull
         fi
+        if [ $? -ne 0 ]; then
+          err="GIT PULL failed in $(pwd) for branch '$branch'"
+        fi
     else
-        echo -e "\e[1;31m ************* Remote not found for branch '$branch' in $(pwd)\e[0m"
+        err="Remote not found in $(pwd) for branch '$branch'"
     fi
   else
-    echo -e "\e[1;31m ************* Unable to get current branch in $(pwd)\e[0m"
+    err="Unable to get current branch in $(pwd)"
+  fi
+
+  if [ -n "$err" ]; then
+    echo -e "\e[1;31m ***** $err\e[0m"
+    errors+=("$err")
   fi
 }
-
 
 cd "$MW_INSTALL_PATH"
 pull
@@ -38,3 +48,9 @@ do
 done
 
 php maintenance/update.php --quick
+
+if [ ${#errors[@]} -ne 0 ]; then
+  echo
+  echo -e "\e[1;31m ************* Errors ***********\e[0m"
+  printf -- '* %s\n' "${errors[@]}"
+fi
