Have foreachwiki exit with non-zero status if any wiki fails
This allows puppet to detect the error here, rather than make it look
like a later step is at fault or there is an ordering problem.

Change-Id: Ia6563ce21002bfedac8ddd36475172b76a22e5a2

diff --git a/puppet/modules/mediawiki/templates/multiwiki/foreachwiki.erb b/puppet/modules/mediawiki/templates/multiwiki/foreachwiki.erb
--- a/puppet/modules/mediawiki/templates/multiwiki/foreachwiki.erb
+++ b/puppet/modules/mediawiki/templates/multiwiki/foreachwiki.erb
@@ -6,10 +6,20 @@
 CMD=$1
 shift
 
+FAILURES=0
 for db in $(alldbs); do
   echo -----------------------------------------------------------------
   echo $db
   echo -----------------------------------------------------------------
   mwscript "$CMD" --wiki=$db "$@" |
   sed -u "s/^/$db:  /"
+
+  if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
+      ((FAILURES++))
+  fi
 done
+
+if [[ $FAILURES -ne 0 ]]; then
+    echo "$FAILURES wikis failed." >&2
+    exit 1
+fi
